title: 学术研讨班资料库
description: 收集和展示学术研讨班的周报、演示文稿和摘要
baseurl: "/ahu-seminar" # 根据您的GitHub仓库名称设置
url: "https://wushixuan238.github.io" # 您的GitHub Pages URL

# 构建设置
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 集合设置
collections:
  meetings:
    output: true
    permalink: /meetings/:path/
  members:
    output: true
    permalink: /members/:path/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# 社交媒体设置（可选）
# github_username: your-github-username
# twitter_username: your-twitter-username

# 集合设置
collections:
  seminar_topics:
    output: true
    permalink: /topics/:path/
    
# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "seminar_topics"
    values:
      layout: "topic"
  - scope:
      path: ""
    values:
      layout: "default"
